---

- name: Install common dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git-core
    - build-essential
    - python-setuptools
    - python-pip
    - python-dev
    - libpq-dev
    - postgresql-client
    - python-psycopg2


- name: Install virtualenv
  pip:
    name: virtualenv


- name: Install supervisor
  include: supervisor.yml


- name: Add users
  include: add_users.yml


- name: Set hostname
  hostname: name={{ hostname_base }}-{{ hostname_suffix }}
