---

- name: Install supervisor
  apt:
    name: supervisor
    state: latest
    update_cache: yes


- name: Create log directory
  file:
    path: /var/log/supervisor
    state: directory


- name: Create log file
  file:
    path: /var/log/supervisor/supervisord.log
    state: touch


- name: Configure supervisor
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/supervisord.conf
  notify: restart supervisor
