# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20150418_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='flatpage_ptr',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
