# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20150910_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(),
        ),
    ]
