Vagrant.configure(2) do |config|

  config.vm.define "yanlog_vagrant" do |server|

    server.vm.box = "ubuntu14.04"

    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
   
    server.vm.network "forwarded_port", guest: 80, host: 9003

  end
end

