---

- name: Create directories for the application
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - /srv/www/{{ domain_name }}/code
    - /srv/www/{{ domain_name }}/static
    - /srv/www/{{ domain_name }}/venv
    - /srv/www/{{ domain_name }}/envdir
    - /srv/www/{{ domain_name }}/log
    - /srv/www/{{ domain_name }}/uwsgi/etc
    - /srv/www/{{ domain_name }}/uwsgi/sock
    - /srv/www/{{ domain_name }}/nginx
