---

- name: Base setup for application deployment
  hosts: web
  user: ubuntu
  sudo: yes
  sudo_user: root
  gather_facts: no

  vars:
    app_name: yanlog

  roles:
    - common

  tags:
    - common


- name: Set up webtier on the server
  hosts: web
  user: ubuntu
  sudo: yes
  sudo_user: root
  gather_facts: no

  roles:
    - webtier

  tags:
    - webtier
